geometry_msgs/Pose pose
bool local true
float64 duration
---
geometry_msgs/Pose pose #final relative position
bool target_reached #if guppy made it to the target pose
---
geometry_msgs/Pose progress #current progess relative to start
